apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: ttm-triton
spec:
  predictor:
    triton:
      storageUri: http://ubuntu-dev-1-svc.default.svc.cluster.local:8080/triton_model_repository.tar.gz
      runtimeVersion: "23.10-py3"
