apiVersion: v1
kind: Pod
metadata:
  name: pytorch-dev
  labels:
    app: pytorch-dev
spec:
  restartPolicy: Always
  containers:
    - name: pytorch
      image: pytorch/pytorch:2.4.1-cuda12.1-cudnn9-runtime
      workingDir: /workspace
      ports:
        - containerPort: 8080
          name: http
      command: ["bash", "-lc"]
      args:
        - |
          set -e
          cd /workspace
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
          mkdir -p /workspace/modelhub
          echo "[OK] Serving /workspace/modelhub on :8080"
          exec python -m http.server 8080 --bind 0.0.0.0 --directory /workspace/modelhub
      resources:
        limits:
          nvidia.com/gpu: "1"
      volumeMounts:
        - name: project
          mountPath: /workspace
  volumes:
    - name: project
      hostPath:
        path: /home/sdn/Workspace/python_study
        type: Directory
