name: "ttm"
backend: "python"
max_batch_size: 0

input [
  {
    name: "y"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
  {
    name: "fh"
    data_type: TYPE_INT64
    dims: [ -1 ]
  }
]

output [
  {
    name: "y_pred"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]
