.PHONY: triton clean

triton:
	bash /root/Workspace/python_study/src/tmm/scripts/build_triton_venv.sh

clean:
	rm -f /root/Workspace/python_study/src/tmm/triton_model_repository.tar.gz
	bash /root/Workspace/python_study/src/tmm/scripts/build_triton_venv.sh --clean
